name: try-gmt-python
channels:
    - conda-forge
    - conda-forge/label/dev
dependencies:
    - python=3.6
    - pip=9.0.1
    - gmt=6.0.0a12
    - numpy=1.14.0
    - pandas=0.22.0
    - matplotlib=2.2.0
    - jupyter=1.0.0
    - notebook=5.4.0
    - ipython=6.2.1
    - pip:
        - https://github.com/GenericMappingTools/gmt-python/archive/bc19559a525a511b994f6d3e6c26dd276f2c6a18.zip
