name: try-gmt-python
channels:
    - conda-forge
    - conda-forge/label/dev
dependencies:
    - python=3.6
    - pip=9.0.*
    - gmt=6.0.0a16
    - numpy=1.14.*
    - pandas=0.23.*
    - xarray=0.10.*
    - packaging=17.1
    - jupyter=1.0.0
    - notebook=5.5.0
    - ipython=6.4.*
    - pip:
        - https://github.com/GenericMappingTools/gmt-python/archive/0005152780528c7248369fb1446a9670383f2b19.zip
